kind: pipeline
type: docker
name: default

steps:
    - name: build-frontend
      image: node
      commands:
          - lerna bootstrap
          - cd packages/frontend
          - npm install
          - npm run build
